[package]
name = "libnotify-rs"
version = "1.0.0"
edition = "2024"
authors = [ "szymon_jozef"]
description = "Rust bindings for libnotify"
readme = "./README.md"
repository = "https://github.com/szymon-jozef/libnotify-rs"
documentation = "https://szymon-jozef.github.io/libnotify-rs/libnotify_rs/index.html"
license = "MIT"
keywords = [ "bindings", "libnotify", "notificatons" ]
build = "./build.rs"

[dependencies]
clap = {version = "4.6.7", optional = true}

[build-dependencies]
pkg-config = "0.3.34"
bindgen = "0.73.2"

[dev-dependencies]
glib = "0.22.10"
serial_test = "4.0.1"

[features]
clap = [ "dep:clap" ]
